export default [
  {
    id: 'menu1',
    name: 'Home',
    to: 'home',
    icon: 'home',
    subMenu: [],
  },
  {
    id: 'menu2',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu21',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu22',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu3767',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu37671',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu37672',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu300',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu3001',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu3002',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu56',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu561',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu562',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu54',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu541',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu542',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu377',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu3771',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu3772',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu39',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu391',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu392',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu33',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu331',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu332',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu30',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu301',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu302',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu31',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu311',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu312',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
  {
    id: 'menu4',
    name: 'Other Page',
    to: '#',
    icon: 'page',
    subMenu: [
      {
        id: 'menu41',
        name: 'About',
        to: 'about',
        icon: '',
        subMenu: [],
      },
      {
        id: 'menu42',
        name: 'Contact',
        to: 'contact',
        icon: '',
        subMenu: [],
      },
    ],
  },
];
